# -*- coding: utf-8 -*-
"""Bar Plots & Scatter Plots.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PkXBIca2naMw8oTGidj6WiH8K7klpR4e
"""

import pandas as pd
df = pd.read_csv('fandango_scores.csv')
df.head()

norm_reviews = df[["FILM", 'RT_user_norm', "Metacritic_user_nom", "IMDB_norm", "Fandango_Ratingvalue", "Fandango_Stars"]].copy()
norm_reviews.head()

import matplotlib.pyplot as plt
fig, ax=plt.subplots()
## positions of the left side of the 5 bars [0.75, 1.75, 2.75, 3.75, 4.75]
import numpy as np
bar_positions = np.arange(5) + 0.75

## Heights of the bars, In our cases, the avergae rating for the first movie in the dataset.
num_columns = ['RT_user_norm',"Metacritic_user_nom", "IMDB_norm", "Fandango_Ratingvalue", "Fandango_Stars"]
bar_heights = norm_reviews[num_columns].iloc[0].values
ax.bar(bar_positions, bar_heights, 0.5)
tick_positions = range(1,6)
ax.set_xlabel("Rating Source")
ax.set_ylabel("Average Rating")
ax.set_title("Average User Rating For Avengers: Age of Ultron")
ax.set_xticks(tick_positions)
ax.set_xticklabels(num_columns, rotation=90)
plt.show()

## Horizontal barplot
fig, ax = plt.subplots()
bar_widths = norm_reviews[num_columns].iloc[0].values
bar_positions = np.arange(5) +0.75
ax.barh(bar_positions, bar_widths, 0.5)
ytick_positions = range(1,6)
ax.set_xlabel("Average Rating")
ax.set_ylabel("Rating Source")
ax.set_title("Average User Rating for Avengers: Age of Ultron(2015)")
ax.set_yticks(ytick_positions)
ax.set_yticklabels(num_columns)
plt.show()

## scatter plot for 2 columns
fig, ax = plt.subplots()
x = norm_reviews["Fandango_Ratingvalue"].values
y = norm_reviews["RT_user_norm"].values
ax.scatter(x,y)
ax.set_xlabel("Fandango")
ax.set_ylabel("Rotten Tomatoes")
plt.show()

# subplots
fig = plt.figure(figsize=(5,10))
fig, ax = plt.subplots()
ax1 = fig.add_subplot(2,1,1)
ax2 = fig.add_subplot(2,1,2)
ax1.scatter(df["Fandango_Ratingvalue"].values, df['RT_user_norm'].values)
ax1.set_xlabel('Fandango')
ax1.set_ylabel("Rotten Tomatoes")
ax2.scatter(df["RT_user_norm"].values, df["Fandango_Ratingvalue"].values,c="red")
ax2.set_xlabel("Rotten Tomatoes")
ax2.set_ylabel("Fandango")
plt.show()

