# -*- coding: utf-8 -*-
"""Avocado Prices -Data Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X1EauB7fAVtW3R2nR8Ri1jmhjSqTr0EB
"""

import pandas as pd
df= pd.read_csv("avocado.csv")

df

df.head()

df.head(3)

df.tail(6)

df["AveragePrice"].head()

df.AveragePrice.head()

import matplotlib.pyplot as plt
albany_df=df[df["region"]=="Albany"]

albany_df.head()

albany_df.index

albany_df.set_index("Date")

albany_df.head()

albany_df["AveragePrice"].plot()

