# -*- coding: utf-8 -*-
"""Groupby-Day 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-XhRvZxs8GgfwE7UGgWd3_ptbZQPqdc_
"""

import pandas as pd
df =pd.read_csv("wage.csv", encoding="latin")

df.to_csv("minwage.csv", encoding="utf-8")
df = pd.read_csv("minwage.csv")
df.head()

df["State"].unique()

# groupby function
gb = df.groupby("State")
gb.get_group("Alabama").set_index("Year").head()

# Grouping the values of states as columns with row values of Low.2018 
act_min_wage = pd.DataFrame()
for name,group in df.groupby("State"):
  if act_min_wage.empty:
    act_min_wage = group.set_index("Year")[["Low.2018"]].rename(columns={"Low.2018":name})
  else:
    act_min_wage = act_min_wage.join(group.set_index("Year")[["Low.2018"]].rename(columns={"Low.2018":name})) 

act_min_wage.head()

act_min_wage.describe()

# Shows corelation between various values
act_min_wage.corr().head()

df.head()

issues_df = df[df["Low.2018"]==0]
issues_df.head()

issues_df["State"].unique()

# above data is prblematic for our visualization
# removing the data
import numpy as np
# axis = 1 for columns, defualt is 0 for rows
act_min_wage.replace(0,np.NaN).dropna(axis=1).corr().head()
act_min_wage.describe()

min_wage_corr = act_min_wage.replace(0,np.NaN).dropna(axis=1).corr()

for problem in issues_df["State"].unique():
  if problem in min_wage_corr.columns:
    print("Missing something here....")

grouped_issues = issues_df.groupby("State")
grouped_issues.get_group("Alabama").head(3)

# checking sum low.2018
grouped_issues.get_group("Alabama")["Low.2018"].sum()

# checking issues in our group
for state, data in grouped_issues:
  if data["Low.2018"].sum()!=0.0:
    print("some data found for", state)

